{
    'name': 'custom_max',
    'version': '17.0',
    'license': 'LGPL-3',
    'category': 'BOM',
    'sequence': -500,
    'summary': 'Manage orders and sales orders',
    'depends': ['base', 'product', 'mrp', 'purchase'],
    'data': ['view\product_template_views.xml',
             'view/name_change.xml',
             'view/vendor.xml',
             'view/confirmation.xml',
             'wizard/confirm.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
